export const SUBSCRIPTION_TRACKS = {
  TRADER: 'trader',
  MIZIGO: 'mizigo',
};

export const SUBSCRIPTION_FEATURES = {
  INVENTORY_LEDGER: 'inventory-ledger',
  METADATA_BUCKET: 'metadata-bucket',
  ESCROW_CLIENT: 'escrow-client',
  MANUAL_CRM: 'manual-crm',
  REVENUE_TRACKER: 'revenue-tracker',
  QR_HANDSHAKE: 'qr-handshake',
  AUTOMATED_CRM_ENGINE: 'automated-crm-engine',
  GUARDIAN_REGIONAL_ALARM: 'guardian-regional-alarm',
  SOURCING_BRIDGE_LITE: 'sourcing-bridge-lite',
  CFO_LITE_HOOK: 'cfo-lite-hook',
  HEALTH_GAUGE: 'health-gauge',
  CLEARANCE_AGENT: 'clearance-agent',
  CFO_AGENTIC_ENGINE: 'cfo-agentic-engine',
  AMORTIZED_CAPEX: 'amortized-capex',
  CASHFLOW_PREDICTION: 'cashflow-prediction',
  MARKET_LED_PRODUCTION: 'market-led-production',
  BULK_MARKETING_ENGINE: 'bulk-marketing-engine',
  GROUP_BUY_LOGISTICS_TRIGGER: 'group-buy-logistics-trigger',
  MACRO_SCARCITY_GUARD: 'macro-scarcity-guard',
  CAPEX_MAINTENANCE_GUARD: 'capex-maintenance-guard',
  AUTOMATED_REGIONAL_LEVIES: 'automated-regional-levies',
  EXTERNAL_API_WEBHOOKS: 'external-api-webhooks',
  MARKET_HEATMAPS: 'market-heatmaps',
  DIGITAL_WAYBILL: 'digital-waybill',
  UNIFIED_BOOKING_QUEUE: 'unified-booking-queue',
  GROUP_BUY_MATCHER: 'group-buy-matcher',
  SHARED_COST_CALCULATOR: 'shared-cost-calculator',
  ROUTE_INTELLIGENCE_LITE: 'route-intelligence-lite',
  MIZIGO_CFO_HOOK: 'mizigo-cfo-hook',
  PREDICTIVE_ROUTE_INTELLIGENCE: 'predictive-route-intelligence',
  FLEET_API: 'fleet-api',
  MACRO_SCARCITY_BRIDGE: 'macro-scarcity-bridge',
};

const F = SUBSCRIPTION_FEATURES;

export const TRADER_PLANS = [
  {
    id: 'trader_solo',
    track: SUBSCRIPTION_TRACKS.TRADER,
    name: 'Lango Solo',
    priceLabel: 'KSh 500',
    differentiator: 'Manual Operations',
    description: 'Digital ledger and transaction tools without automated intelligence agents.',
    featureKeys: [
      F.INVENTORY_LEDGER,
      F.METADATA_BUCKET,
      F.ESCROW_CLIENT,
      F.MANUAL_CRM,
      F.REVENUE_TRACKER,
      F.QR_HANDSHAKE,
    ],
  },
  {
    id: 'trader_essential',
    track: SUBSCRIPTION_TRACKS.TRADER,
    name: 'Lango Essential',
    priceLabel: 'KSh 2,500',
    differentiator: 'Reactive Automation',
    description: 'Automated alerts and cost tracking to prevent stockouts and protect margins.',
    featureKeys: [
      F.INVENTORY_LEDGER,
      F.METADATA_BUCKET,
      F.ESCROW_CLIENT,
      F.MANUAL_CRM,
      F.REVENUE_TRACKER,
      F.QR_HANDSHAKE,
      F.AUTOMATED_CRM_ENGINE,
      F.GUARDIAN_REGIONAL_ALARM,
      F.SOURCING_BRIDGE_LITE,
      F.CFO_LITE_HOOK,
      F.HEALTH_GAUGE,
      F.CLEARANCE_AGENT,
    ],
  },
  {
    id: 'trader_growth',
    track: SUBSCRIPTION_TRACKS.TRADER,
    name: 'Lango Growth',
    priceLabel: 'Custom',
    differentiator: 'Predictive Maneuverability',
    description: 'Forecasting and market-led production intelligence for larger operators.',
    featureKeys: [
      F.INVENTORY_LEDGER,
      F.METADATA_BUCKET,
      F.ESCROW_CLIENT,
      F.MANUAL_CRM,
      F.REVENUE_TRACKER,
      F.QR_HANDSHAKE,
      F.AUTOMATED_CRM_ENGINE,
      F.GUARDIAN_REGIONAL_ALARM,
      F.SOURCING_BRIDGE_LITE,
      F.CFO_LITE_HOOK,
      F.HEALTH_GAUGE,
      F.CLEARANCE_AGENT,
      F.CFO_AGENTIC_ENGINE,
      F.AMORTIZED_CAPEX,
      F.CASHFLOW_PREDICTION,
      F.MARKET_LED_PRODUCTION,
      F.BULK_MARKETING_ENGINE,
      F.GROUP_BUY_LOGISTICS_TRIGGER,
    ],
  },
  {
    id: 'trader_enterprise',
    track: SUBSCRIPTION_TRACKS.TRADER,
    name: 'Lango Enterprise',
    priceLabel: 'Custom',
    differentiator: 'Macro-Intelligence & Integration',
    description: 'Cross-county intelligence, levy automation, APIs, and supply corridor heatmaps.',
    featureKeys: [
      F.INVENTORY_LEDGER,
      F.METADATA_BUCKET,
      F.ESCROW_CLIENT,
      F.MANUAL_CRM,
      F.REVENUE_TRACKER,
      F.QR_HANDSHAKE,
      F.AUTOMATED_CRM_ENGINE,
      F.GUARDIAN_REGIONAL_ALARM,
      F.SOURCING_BRIDGE_LITE,
      F.CFO_LITE_HOOK,
      F.HEALTH_GAUGE,
      F.CLEARANCE_AGENT,
      F.CFO_AGENTIC_ENGINE,
      F.AMORTIZED_CAPEX,
      F.CASHFLOW_PREDICTION,
      F.MARKET_LED_PRODUCTION,
      F.BULK_MARKETING_ENGINE,
      F.GROUP_BUY_LOGISTICS_TRIGGER,
      F.MACRO_SCARCITY_GUARD,
      F.CAPEX_MAINTENANCE_GUARD,
      F.AUTOMATED_REGIONAL_LEVIES,
      F.EXTERNAL_API_WEBHOOKS,
      F.MARKET_HEATMAPS,
    ],
  },
];

export const MIZIGO_PLANS = [
  {
    id: 'mizigo_solo',
    track: SUBSCRIPTION_TRACKS.MIZIGO,
    name: 'Mizigo Solo',
    priceLabel: 'Entry',
    differentiator: 'Manual Booking & Verification',
    description: 'For independent drivers managing one truck and single-trip verification.',
    featureKeys: [
      F.DIGITAL_WAYBILL,
      F.QR_HANDSHAKE,
      F.UNIFIED_BOOKING_QUEUE,
      F.REVENUE_TRACKER,
    ],
  },
  {
    id: 'mizigo_pro',
    track: SUBSCRIPTION_TRACKS.MIZIGO,
    name: 'Mizigo Pro',
    priceLabel: 'Custom',
    differentiator: 'Reactive Efficiency',
    description: 'Load factor optimization for fleet owners with shared-cost automation.',
    featureKeys: [
      F.DIGITAL_WAYBILL,
      F.QR_HANDSHAKE,
      F.UNIFIED_BOOKING_QUEUE,
      F.REVENUE_TRACKER,
      F.GROUP_BUY_MATCHER,
      F.SHARED_COST_CALCULATOR,
      F.ROUTE_INTELLIGENCE_LITE,
      F.MIZIGO_CFO_HOOK,
    ],
  },
  {
    id: 'mizigo_enterprise',
    track: SUBSCRIPTION_TRACKS.MIZIGO,
    name: 'Mizigo Enterprise',
    priceLabel: 'Custom',
    differentiator: 'Predictive Logistics & Asset Protection',
    description: 'Predictive routing, maintenance, scarcity bridge, and fleet integrations.',
    featureKeys: [
      F.DIGITAL_WAYBILL,
      F.QR_HANDSHAKE,
      F.UNIFIED_BOOKING_QUEUE,
      F.REVENUE_TRACKER,
      F.GROUP_BUY_MATCHER,
      F.SHARED_COST_CALCULATOR,
      F.ROUTE_INTELLIGENCE_LITE,
      F.MIZIGO_CFO_HOOK,
      F.PREDICTIVE_ROUTE_INTELLIGENCE,
      F.CAPEX_MAINTENANCE_GUARD,
      F.MACRO_SCARCITY_BRIDGE,
      F.FLEET_API,
    ],
  },
];

export const ALL_PLANS = [...TRADER_PLANS, ...MIZIGO_PLANS];

export const FEATURE_LABELS = {
  [F.INVENTORY_LEDGER]: 'Manual inventory ledger (up to 30 SKUs)',
  [F.METADATA_BUCKET]: 'Metadata bucket (Harvest Date, Batch ID)',
  [F.ESCROW_CLIENT]: 'Standard escrow client',
  [F.MANUAL_CRM]: 'Manual CRM contact table',
  [F.REVENUE_TRACKER]: 'Basic revenue tracker',
  [F.QR_HANDSHAKE]: 'QR scan handshake',
  [F.AUTOMATED_CRM_ENGINE]: 'Automated CRM restock SMS engine',
  [F.GUARDIAN_REGIONAL_ALARM]: 'Guardian regional scarcity alarm',
  [F.SOURCING_BRIDGE_LITE]: 'Sourcing bridge (lite)',
  [F.CFO_LITE_HOOK]: 'CFO lite hook',
  [F.HEALTH_GAUGE]: '24-hour health gauge',
  [F.CLEARANCE_AGENT]: 'Point-8 clearance agent',
  [F.CFO_AGENTIC_ENGINE]: 'Full agentic CFO engine',
  [F.AMORTIZED_CAPEX]: 'Amortized CAPEX calculation',
  [F.CASHFLOW_PREDICTION]: 'Cash flow prediction',
  [F.MARKET_LED_PRODUCTION]: 'Market-led production dashboard',
  [F.BULK_MARKETING_ENGINE]: 'Bulk marketing engine',
  [F.GROUP_BUY_LOGISTICS_TRIGGER]: 'Group-buy logistics trigger',
  [F.MACRO_SCARCITY_GUARD]: 'Macro-scarcity guard',
  [F.CAPEX_MAINTENANCE_GUARD]: 'CAPEX maintenance guard',
  [F.AUTOMATED_REGIONAL_LEVIES]: 'Automated regional levies',
  [F.EXTERNAL_API_WEBHOOKS]: 'External API and webhooks',
  [F.MARKET_HEATMAPS]: 'Market heatmaps',
  [F.DIGITAL_WAYBILL]: 'Digital waybill',
  [F.UNIFIED_BOOKING_QUEUE]: 'Unified booking queue',
  [F.GROUP_BUY_MATCHER]: 'Group-buy matcher',
  [F.SHARED_COST_CALCULATOR]: 'Shared-cost calculator',
  [F.ROUTE_INTELLIGENCE_LITE]: 'Route intelligence (lite)',
  [F.MIZIGO_CFO_HOOK]: 'Mizigo CFO hook',
  [F.PREDICTIVE_ROUTE_INTELLIGENCE]: 'Predictive route intelligence',
  [F.FLEET_API]: 'Fleet API and webhooks',
  [F.MACRO_SCARCITY_BRIDGE]: 'Macro-scarcity bridge',
};
